name: Ubuntu 24.04 CI (fast-math)

on: [push, pull_request]

jobs:
  ubuntu-build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Use cmake
        run: |
          mkdir build &&
          cd build &&
          cmake -DCMAKE_CXX_FLAGS="-ffast-math" -DFASTFLOAT_TEST=ON ..  &&
          cmake --build .   &&
          ctest --output-on-failure
